### ISSUE TITLE
Issue with Media order on Django 2.x when used with autocomplete_fields

### ISSUE THREAD

**Issue by wallforfry** [theatlantic/django-nested-admin#118]
Hi !

I've got an issue with django-nested-admin and Django 2.1.4.

When I press "Add" or "remove" button it appens like if javascript does not work.
But when I check js console, there is not anything.

**Comment by fdintino** [comment]
#25 was a misreported issue. The `href` attribute on those links doesn't matter, because the click event handler ignores it completely.

The unit tests run on Django 2.1 and 2.2, and those are pretty exhaustive, so if the 'Add' button doesn't work for you then there's some other factor at play. Could you post the code for your `ModelAdmin` classes, and include any relevant information about django admin customizations or addons?

**Comment by bmeyer71** [comment]
I've run into the same issue with Django 2.2 and nested 3.2.1. However, I've narrowed it down to using the **autocomplete_fields** on the first level of nested inlines. Without that option specified the "Add another" link works on that level as well as the inline nested within as well.

Hopefully that can help troubleshoot the issue further.
If more info is needed, please let me know.

**Comment by fdintino** [comment]
That is extremely helpful, enough so that I've got a fix just about ready.
