### ISSUE TITLE
IntegrityError when deleting item - looks related to "Suppress validation errors of descendent inlines of deleted forms"

### ISSUE THREAD

**Issue by bmeyer71** [theatlantic/django-nested-admin#135]
It seems the issue I've run into is related to the one worked on in "Suppress validation errors of descendent inlines of deleted forms". The fix that was applied recently has resolved part of the problem, however there still seems to be an issue.
Hopefully I can describe it clearly enough to make sense :)

I have models set up like the following:

Account
Resource - ForeignKey to Account
UserManager - ForeignKey to Account
ResourceAccess - ForeignKey to UserManager & ForeignKey to Resource

The updates in the latest fix has allowed me to delete a "UserManager" instance and it's related "ResourceAccess" instance.
However, I am still getting an "IntegrityError" when I delete a "Resource" and that resource is still assigned to a "ResourceAccess" instance.

If I remove the nested-admin model inheritance in the admin for both the parent and the inlines, I am able to delete the "Resource" instance and it deletes the instances that are related to it as well.

**Comment by fdintino** [comment]
I'm not sure I 100% follow. Could you post the minimal models.py and admin.py I can use to reproduce the issue?

**Comment by bmeyer71** [comment]
Hope this helps. I removed what shouldn't really be needed.

```
class Account(TrackingFields):
    name = models.CharField(
        max_length=25,
        unique=True,
        )
    profiles = models.ManyToManyField(
        'Profile',
        related_name='accounts',
        blank=True,
        )


class PrimaryResource(TrackingFields):
    account = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        )
    resource_type = models.CharField(
        max_length=7,
        choices=RESOURCE_TYPE_CHOICES,
        default=WEBSERVER,
        )
    resource = models.OneToOneField(
        Droplet,
        on_delete=models.CASCADE,
        related_name='do_server',
    )


class UserManager(TrackingFields):
    account = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        )
    profile = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        )


class ServerAccess(models.Model):
    account_user = models.ForeignKey(
        UserManager,
        on_delete=models.CASCADE,
        )
    server = models.ForeignKey(
        PrimaryResource,
        on_delete=models.CASCADE,
        )

*** ADMIN ***

class PrimaryResourceInline(nested_admin.NestedTabularInline):
    model = PrimaryResource
    autocomplete_fields = ['resource']


class ServerAccessInline(nested_admin.NestedTabularInline):
    model = ServerAccess
    autocomplete_fields = ['server']


class UserManagerAccountInline(nested_admin.NestedTabularInline):
    model = UserManager
    form = UserManagerAdminForm
    autocomplete_fields = ['profile']
    inlines = [ServerAccessInline]


class AccountAdmin(nested_admin.NestedModelAdmin):
    model = Account
    form = AccountAdminForm
    inlines = [PrimaryResourceInline, UserManagerAccountInline]
    search_fields = ['name']

```

**Comment by fdintino** [comment]
So, if I'm understanding correctly, you're referencing the same object at two different levels of nesting. If you delete it in one, but not the other, you get an integrity error. Here's a screenshot of the admin I set up using your example:

![screenshot](https://www.frankiedintino.com/static/misc/nested-admin-issue-135.png)

If you delete the inline for `foo_puppetserver` under Server Access, you'll be able to save without error. Similarly, if you delete the inline for `foo_puppetserver` both in Server Access and Primary Resources, you'll be able to save successfully. The only case where you get an IntegrityError is if you delete `foo_puppetserver` under "Primary Resources" but leave the other inline in place.

The solution would be to change your database schema or your modeladmin definitions so that you don't have two inlines that can reference the same object in the database. I don't think there's a way to sanely handle a situation where the same object appears in multiple places on the admin change form, so I'm not sure there's a django-nested-admin bug here.

It's possible I'm still not understanding the issue though, in which case please let me know what I've got wrong.

**Comment by bmeyer71** [comment]
Awesome! That's exactly the way I have things.
On the flip side, that then means it probably isn't a bug but more a design issue. :(

Until I saw the change that you made in this patch, I was trying to think of a different way to set things up. So far I have not been able to. I'd like to be able to manage both things on the same page, but it seems I may have to leave the Resources part out at least for now.

If you have any suggestions please let me know.

Thank you for the help and for this great package.

**Comment by bmeyer71** [comment]
Actually, I think I have an idea on how I'm going to try to do this. I will look at creating a custom change_form to bring everything together and have menu options to access things like resources and permissions separately. Will probably make the page more manageable over all.

Thanks again.
