### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by faran-mw** [theatlantic/django-nested-admin#158]
I upgraded my project to  Django 3.0.2 and this library (django-nested-admin==3.2.4) fails with the following error when I hit and admin page with nested elements:
"has_add_permission() takes 2 positional arguments but 3 were given"

It happens in "NestedModelAdminMixin._create_formsets" method.

**Comment by fdintino** [comment]
If you're defining your own `has_add_permission` on an inline, it needs to now be `has_add_permission(self, request, obj)`, since Django 2.2. The `TypeError` will get raised in django-nested-admin (that probably ought to be fixed) but the actual issue is that you need to update that method in your admin class.

**Comment by faran-mw** [comment]
Thank you! That was in fact the issue. I had a legacy method defined without an obj parameter. I'll close the issue.
