### ISSUE TITLE
Manually updating sortable_field not being saved

### ISSUE THREAD

**Issue by derblub** [theatlantic/django-nested-admin#225]
I've run into an issue, where users are trying to manually update the `sortable_field`, instead of drag and dropping the objects, which is not being saved. Instead, once the form-save is triggered, the values of the `sortable_field`s get reset to the initial value, as they are visible in the UI.

Is there any way to trigger a new sorting, once a `sortable_field` is manually updated?

**Comment by fdintino** [comment]
Sorry for the long delay in replying here: usually we just hide the sortable field. Is that not an option for you? Changing an order field is not very intuitive and it can be ambiguous as well (what should happen in a list of 3 items if the last one's sortable field is changed from `2` to `1`, so that the items in the inline are now `0`, `1`, and `1`?)
