### ISSUE TITLE
Nested many-to-many fields not working

### ISSUE THREAD

**Issue by nathan-osman** [theatlantic/django-nested-admin#35]
I am running into a problem with the following models which nest many-to-many fields:

#### models.py

    from django.db import models

    class Part(models.Model):
        name = models.CharField(max_length=40)

    class Component(models.Model):
        name = models.CharField(max_length=40)
        parts = models.ManyToManyField(Part)

    class Car(models.Model):
        name = models.CharField(max_length=40)
        components = models.ManyToManyField(Component)

#### admin.py

    from django.contrib import admin
    import nested_admin

    from .models import Part, Component, Car

    class PartInline(nested_admin.NestedTabularInline):
        model = Component.parts.through

    class ComponentInline(nested_admin.NestedTabularInline):
        model = Car.components.through
        exclude = ('parts',)
        inlines = (PartInline,)

    @admin.register(Car)
    class CarInline(nested_admin.NestedModelAdmin):
        exclude = ('components',)
        inlines = (ComponentInline,)

When I attempt to create a car in the admin, I end up with the following error:

    ValueError at /admin/app/car/add/
    'app.Component_parts' has no ForeignKey to 'app.Car_components'.

Am I doing something wrong or is this a bug?

**Comment by fdintino** [comment]
I'm afraid this is not a bug. A similar limitation exists in Django itself, it's just harder to encounter because inlines can only be nested one-deep. Basically, the ForeignKey direction of inlines is only allowed to go one way (from the inline to the parent). This is the case for a number of reasons, one of which is that after a form submission on the add page it first saves the main form, so it can get its primary key, and then sets that foreign key on the inlines. To have the relationship go the other direction would mean that it would have to reverse this order in some cases, and there's no elegant way to do this.

There's an even clearer intuitive reason why representing a many-to-many relationship in inlines wouldn't work. Consider the following example data from your models above (assuming this is the data for one particular car):

<table border="1" cellspacing="0" cellpadding="3">
    <tr>
        <th colspan="2">part</th>
        <th rowspan="5"></th>
        <th colspan="2">component</th>
        <th rowspan="5"></th>
        <th colspan="3">partcomponent</th>
    </tr>
    <tr>
        <th>id</th>
        <th>name</th>
        <th>id</th>
        <th>name</th>
        <th>id</th>
        <th>part_id</th>
        <th>component_id</th>
    </tr>
    <tr>
        <td>1</td>
        <td>A</td>
        <td>1</td>
        <td>X</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
    </tr>
    <tr>
        <td>2</td>
        <td>B</td>
        <td>2</td>
        <td>Y</td>
        <td>2</td>
        <td>1</td>
        <td>3</td>
    </tr>
    <tr>
        <td>3</td>
        <td>C</td>
        <td>3</td>
        <td>Z</td>
        <td>3</td>
        <td>2</td>
        <td>3</td>
    </tr>
</table>

With inlines, this would be layed out something like:

<table border="1" cellspacing="0" cellpadding="3">
    <tr>
        <th colspan="6">___________________________________Parts___________________________________</th>
    </tr>
    <tr>
        <td colspan="3">Id:   1</td>
        <td colspan="3">Name: A</td>
    </tr>
    <tr>
        <td rowspan="3" colspan="2" width="20%"></td>
        <th colspan="4">______________________________Components______________________________</th>
    </tr>
    <tr>
        <td colspan="2">Id:   1</td>
        <td colspan="2">Name: X</td>
    </tr>
    <tr>
        <td colspan="2">Id:   3</td>
        <td colspan="2">Name: Z</td>
    </tr>
    <tr>
        <td colspan="3">Id:   2</td>
        <td colspan="3">Name: B</td>
    </tr>
    <tr>
        <td rowspan="2" colspan="2" width="20%"></td>
        <th colspan="4">______________________________Components______________________________</th>
    </tr>
    <tr>
        <td colspan="2">Id:   3</td>
        <td colspan="2">Name: Z</td>
    </tr>
    <tr>
        <td colspan="3">Id:   3</td>
        <td colspan="3">Name: C</td>
    </tr>
    <tr>
        <td rowspan="2" colspan="2" width="20%"></td>
        <th colspan="4">______________________________Components______________________________</th>
    </tr>
    <tr>
        <td colspan="4">(none)</td>
    </tr>
</table>

In order for this to be workable, changing the name from "Z" to something else within Part "A"s components inlines would need to simultaneously change the name from the same Component instance under Part "B"s component inlines.

My suggestion is to do the one-deep nesting as you currently are, and then using an appropriate `ManyToManyField` widget for `parts`.

**Comment by nathan-osman** [comment]
Wow, thanks for the explanation. Yeah, I think I'll just implement your suggestion. It's not as elegant as having everything on the same page but it will work.

**Comment by Telofy** [comment]
I’ve run into the same limitation. Would your answer be different if there were only one many-to-many relationship, as in my fictitious example below?

It’d be pretty bad usability for our users if they had to enter the author names in a popup with only one field, and adding author is going to be much more common than finding that the author already exists and selecting it. As an alternative I’m considering denormalizing with a Postgres array field.

### `models.py`

    from django.db import models


    class Author(models.Model):
        name = models.CharField(max_length=80)


    class Book(models.Model):
        title = models.CharField(max_length=80)
        authors = models.ManyToManyField(Author)


### `admin.py`

    import nested_admin
    from django.contrib import admin
    from .models import Author, Book


    class AuthorInline(nested_admin.NestedTabularInline):
        model = Author


    class AuthorRelationInline(nested_admin.NestedTabularInline):
        model = Book.authors.through
        inlines = (AuthorInline,)


    @admin.register(Book)
    class BookInline(nested_admin.NestedModelAdmin):
        exclude = ('authors',)
        inlines = (AuthorRelationInline,)

**Comment by fdintino** [comment]
Correct, the limitation would be the same even with just one many to many relationship.

**Comment by rodrigodealexandre** [comment]
Hi there,

Just wondering if there is any update that made this possible?
I am trying to find some new information regarding it, but I have not succeeded.

Thanks.
