### ISSUE TITLE
save() prohibited to prevent data loss due to unsaved related object

### ISSUE THREAD

**Issue by romesh-mccullough** [theatlantic/django-nested-admin#46]
Hello!  First off, thanks for the great project.

Using:
django-1.9.7
django-nested-admin-3.0.5 
django-grappelli-2.8.1

And with a quick contrived example app that looks like the following:

```
# models.py
class Main(models.Model):
    text = models.CharField(max_length=255, blank=True, null=True)

class Level1(models.Model):
    main = models.ForeignKey(Main)

class Level2(models.Model):
    level_1 = models.ForeignKey(Level1)
    text = models.CharField(max_length=255, blank=True, null=True)

# admin.py
class Level2InlineAdmin (nested_admin.NestedTabularInline):
  model = Level2
  extra = 0

class Level1InlineAdmin (nested_admin.NestedStackedInline):
  model = Level1
  extra = 0
  inlines = [ Level2InlineAdmin, ]

class MainAdmin (nested_admin.NestedModelAdmin):
  inlines = [ Level1InlineAdmin, ]

admin.site.register(Main, MainAdmin)
admin.site.register(Level1)
admin.site.register(Level2)
```

I get the error in the title the first time I attempt to create a `Main` item and add a `Level2` item.

If I add a field of any type to `Level1` and give it a value in the admin form, I am able to save the object and all subsequent modifications work.  However, if I leave that hypothetical field blank I also get the same error.

It seems like there's a problem saving the intermediate `Level1` model if the admin form didn't detect changes to that model specifically.  Unfortunately I'm relatively new to Django, and am uncertain where to look for this kind of fix.

Please let me know if there's any more detail I can provide, or if I just have a fundamental misunderstanding of something :)

Thanks!

**Comment by fdintino** [comment]
Turns out this isn't fixed just yet. Working on it.

**Comment by fdintino** [comment]
It's fixed now.

**Comment by m-sanders** [comment]
Excellent project, but I feel that this might not be fixed yet. Maybe I am doing something wrong?

**Steps taken:**

* Copied the above example using 3.0.8 and Django 1.9.7.
* Expanded down to level 2 and entered some text only in the Level 2 `text` field.
* Saved.

**Expected result**

Validation error

**Actual Result**

`save() prohibited to prevent data loss due to unsaved related object`.

**Comment by fdintino** [comment]
Actually, it appears that I was incorrect above. I tested myself using your setup, and then wrote a unit test for it ([see here](https://github.com/theatlantic/django-nested-admin/commit/f3beb4561a5afeb0e83d6e824df3d4cfd0b5e10b)), and I do not get the `save() prohibited to prevent data loss due to unsaved related object` error. And the test [passes in Jenkins](https://travis-ci.org/theatlantic/django-nested-admin/builds/145640910). Is it possible that you have two installations of django-nested-admin in your python path, and perhaps the older one is active? From the manage shell, you can run:

```python
__import__('nested_admin').__version__
```

To see what version is active in the path.

**Comment by m-sanders** [comment]
Well it turns out that this is a fun one. `'nested_admin'` must be before `'django.contrib.admin'` in `INSTALLED_APPS`. If it comes after then `all_valid()` does not get patched by monkey business. The test suite runs with `'nested_admin'` as the first entry.

Maybe a documentation update is required. By convention most Django projects list Django apps, third party apps then their own apps.

**Comment by fdintino** [comment]
Oh, yes that would do it. It's not uncommon for admin-customization libraries (like grappelli, for instance) to need to come before `'django.contrib.admin'` in `INSTALLED_APPS`, so if that's now the case I don't see a reason to try to work around that (and in this case I'm not sure it can be avoided), but it absolutely should be noted in the README and documentation. I'm sorry you had to waste your time trying to figure this out, but thank you nonetheless for making the effort.

**Comment by fdintino** [comment]
I'm closing this ticket in favor of #56, which is explicitly about the `INSTALLED_APPS` ordering.
