### ISSUE TITLE
Uncaught TypeError: i is not a function

### ISSUE THREAD

**Issue by ilizaran** [theatlantic/django-nested-admin#75]
I get this error when launching my application and I can't add new rows.

I'm using:
appdirs==1.4.3
Django==1.10.7
django-autocomplete-light==3.2.4
django-debug-toolbar==1.7
django-grappelli==2.9.1
django-nested-admin==3.0.17
django-tabbed-admin==1.0.1
django-tables2==1.4.2
mysql==0.0.1
MySQL-python==1.2.5
packaging==16.8
pkg-resources==0.0.0
pyparsing==2.2.0
python-monkey-business==1.0.0
pytz==2017.2
six==1.10.0
sqlparse==0.2.3

when I remove django-tabbed-admin there aren't any problem.

in admin.py:
class MyAdmin(NestedModelAdmin, TabbedModelAdmin):
...

Thanks.

**Comment by fdintino** [comment]
If you are extending another `ModelAdmin`, you will want to use `NestedModelAdminMixin` rather than `NestedModelAdmin`. That said, we don't support django-tabbed-admin; doing so would require changes to that project. There is an [open issue](https://github.com/omji/django-tabbed-admin/issues/15) on the github for `django-tabbed-admin` to make it compatible with django-nested-admin.

**Comment by ilizaran** [comment]
Hi, thanks for the quick answer !
