### ISSUE TITLE
performance optimization suggestions

### ISSUE THREAD

**Issue by ryanpineo** [theatlantic/django-nested-admin#76]
Hi,

On one of the projects I work on we are using this library to create 3-4 levels of nesting in the admin.  When an object starts having many sub objects the admin becomes quite slow and eventually takes so long to load that the page times out.

Is there any suggested optimization path for this kind of situation?  I've considered some form of caching to hopefully get the page at least loadable and then disable saving all of the sub objects on that page.

Thank you for reading and any help you can provide.

**Comment by fdintino** [comment]
We have run into this issue as well, and it doesn't lend itself to easy solutions. You can get sizable gains by judicious use of `prefetch_related` in the `__init__` of a class extending `nested_admin.NestedInlineFormSet`. Something like the following:

```python
class D_Inline(nested_admin.NestedStackedInline):
    model = D


class C_Inline(nested_admin.NestedStackedInline):
    model = C


class B_Formset(nested_admin.NestedInlineFormSet):

    def __init__(self, *args, **kwargs):
        super(B_Formset, self).__init__(*args, **kwargs)
        self.queryset = self.queryset.prefetch_related(
            "c_set__some_foreign_key",
            "c_set__some_many_to_many",
            "c_set__d_set",
            # etc...
        )


class B_Inline(nested_admin.NestedStackedInline):
    model = B
    formset = B_Formset
    inlines = [C_Inline]


@admin.register(A)
class A_Admin(nested_admin.NestedModelAdmin):
    inlines = [B_Inline]
```

Model instantiation is very expensive in Django, and because `prefetch_related` uses cached instances of related objects, it can speed up rendering quite a bit. In my experience, the performance benefit from fewer model instantiations is often more significant than is caused by having fewer database queries.

If you can get away with caching certain of the sub objects, you might consider extending `NestedStackedInline` or `NestedTabularInline` in those cases and overriding the `template` attribute with a template that wraps the  inlines in a `{% cache %}` tag.

**Comment by will-emmerson** [comment]
I have tried this method but it doesn't seem to make any difference to the query count at all.
My code looks like this:

```python
class OptionInline(nested_admin.NestedTabularInline):
    model = Option
    classes = 'collapse',


class CompetencyInline(nested_admin.NestedTabularInline):
    model = Competency
    inlines = [
        OptionInline,
    ]
    classes = 'collapse',


class AreaFormset(nested_admin.NestedInlineFormSet):
    def __init__(self, *args, **kwargs):
        super(AreaFormset, self).__init__(*args, **kwargs)
        self.queryset = self.queryset.prefetch_related(
            'competencies__options'
        )


class AreaInline(nested_admin.NestedTabularInline):
    model = Area
    inlines = [
        CompetencyInline,
    ]
    formset = AreaFormset


@admin.register(Assessment)
class AssessmentAdmin(nested_admin.NestedModelAdmin):
    inlines = [
        AreaInline,
    ]
    fields = 'title', 'description',
```

The models are nested like Assessment > Area > Competency > Option.
I have also tried overriding get_queryset() on Assessment admin but it also makes no different.

**Comment by fdintino** [comment]
That's very strange. We've been using this successfully for some time. That said, I realize we don't have unit tests for this, so I can't say for sure it works with all of our supported versions of Django. What version of django are you using? And presumably the prefetch_related is `competencies__options` because you have a custom `related_name` on the field definition in the models?

**Comment by will-emmerson** [comment]
I'm using django 1.11.9 which is the latest version < 2.
Yes, I have defined related name and that code is definitely getting called.
I will try and add a test to the project which uses `assertNumQueries`, it may be something has changed between django versions.
Or it might just be something stupid I'm doing.

**Comment by pacron** [comment]
Maybe it's a bit late, but I managed to improve my web performance a lot by overriding method `formfield_for_foreignkey` in my nested models. The problem of having too much queries is not in the model's queryset, but in the querysets that dropdowns do. This is the code that worked for me (btw, using a profiler I noticed that I was doing approx 7000 queries, with this method the number reduced to 15):

```
class ParticipationInline(nested_admin.NestedTabularInline):
    model = Participation
    def formfield_for_foreignkey(self, db_field, request, **kwargs):
        if db_field.name == "student":
            kwargs["queryset"] = Student.objects.filter(
                course=current_course()
            ).prefetch_related('person', 'person__user')
        return super().formfield_for_foreignkey(db_field, request, **kwargs)
    extra = 1

class ScoringInline(nested_admin.NestedTabularInline):
    model = Scoring
    inlines = [
        ParticipationInline,
    ]
    extra = 0

class ActivitySubdireccion(nested_admin.NestedModelAdmin):
    inlines = [
        ScoringInline,
    ]
```

Sorry if my english is not good, I'm not native speaker :)

**Comment by jakubste** [comment]
I can't get this to work with Django 2.2. Wherever I tried putting `prefetch_related` I keep getting queries that are originated from
```
django/forms/models.py in initial_form_count(574)   return len(self.get_queryset())
```
